Phase02 refactor
Star-Academy/Winter99-Codestar-Mohammad-Kasaei pull request #1
Opened 2021-02-24 16:49 UTC by MKasaei00

2021-02-24 18:51 UTC, RAAvenger requested changes
یکی دو جا اضافه کاری و جای خالی داکیومنت مشکلاتی بودن که به چشم من خوردن.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/InvertedIndex.java
> +    public Set<Document> query(Token token) {
اسم بهتری برای این تابع میتونه انتخاب بشه که بهتر نشون بده این تابع چه کاری انجام میده.
جای جاواداک خالیه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/InvertedIndex.java
> +    public void addDocuments(Map<Document, String> docs) {
جای جاواداک خالیه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/InvertedIndex.java
> +    public void addDocument(Document doc, String content) {
جای جاواداک خالیه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Document.java
> +    private final String fullPath;
با توجه به این پروژه دلیل نگهداری از مسیر کامل هر فایل چیه؟ اضافه کاری نیست؟

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +    private static void startCLI() {
جای جاواداک خالیه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +    private static ArrayList<String> getListOfWords(Scanner scanner) {
جای جاواداک خالیه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +    private static void initializeEngine() {
جای جاواداک خالیه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +            words.add(input);
اگه یه کلمه با حروف بزرگ وارد بشه اینجا بررسیش نمیکنی؟ آیا باگ پیدا کردم؟

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
>          for (String w : words) {
این کلاس هم کار سرچ رو انجام میده و هم صحت کلمات ورودی رو بررسی میکنه؟ بهتر نبود که فقط وظیفه اصلی خودش رو انجام میداد؟

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    public Set<Document> query(ArrayList<String> words) {
جای جاواداک خالیه.
همچنین به نظر میرسه که این تابعه واقعا کوئری نمیزنه، تابع بعدی در اصل کار رو انجام میده. به نظرم انتخاب این اسم برای این تابع یکم باعث گیجی میشه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    public Set<Document> query(Set<Token> plusWords,
جای جاواداک خالیه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    private Set<Document> getUnionOfDocsContainingWords(Set<Token> tokens) {
جاوا دا.....اک.
مخصوصا وقتی اسمش من گیج رو یکم گیجتر میکنه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
>          }
فرض کن بین کلی توکن که 100 تا داکیومنت دارن یه توکن فقط 1 داکیومنت داشته باشه. این الگوریتم میتونه بهینه تر باشه.

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    private Set<Document> getIntersectionOfDocsContainingWords(Set<Token> tokens) {
دیگه نمیگم جاواداک :(
ولی این تابعه کلا گنگه برام

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/TextFileReader.java
> +    public Map<Document, String> readAllFileInFolder(String folderPath) {
پاک کردی جاوا داک رو؟😨

2021-02-24 18:51 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Token.java
> +        return content.toLowerCase();
همه‌ش همین؟

2021-02-24 20:18 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Token.java
> +        return content.toLowerCase();
از نظر مفهومی داره نرمال‌سازی محتوا را انجام میده و یک تابع جدا می‌خواد
ممکنه تو گسترش پروژه کار‌های فراتر از حروف کوچک و بزرگ هم نیاز باشه

2021-02-24 20:22 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
>          for (String w : words) {
وظیفه این کلاس تولید نتیجه سرچ پیشرفته است 
و باید بعد از بررسی و حذف علامت‌های معنادار مانند + و - در ابتدای کلمات تبدیل به توکن بشن 
فکر کنم مناسب باشه

2021-02-24 20:23 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    private Set<Document> getIntersectionOfDocsContainingWords(Set<Token> tokens) {
این مجموعه‌ای از تمام داکیومنت‌هایی را بر می‌گردونه که حداقل شامل یکی از این توکن‌های ورودی باشند

2021-02-24 20:30 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/TextFileReader.java
> +    public Map<Document, String> readAllFileInFolder(String folderPath) {
بعضی تابع‌ها از روی اسم‌شون واقعا واضحه که نیازی به جاوا داک نداره
ولی بودنش ضرر نداره :)

2021-02-24 21:07 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/InvertedIndex.java
> +    public Set<Document> query(Token token) {
جاوا داک اضافه شد 
به نظرم اسم مناسبه 
با این حال توضیحات بیش‌تر را در جاوا داک نوشتم

2021-02-24 21:08 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Document.java
> +    private final String fullPath;
احتمال استفاده‌اش برای نمایش محتوای دقیق فایل به کاربری که در حال کوئری گرفتن هست خیلی زیاده 
برای همین نوشتم

2021-02-24 21:13 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +            words.add(input);
اینجا فعلا رشته‌های خام را ذخیره می‌کنم بعد که می‌خوام به توکن تبدیل کنم نرمال‌سازی میشه

2021-02-25 04:50 UTC, mohammadhheidarzade approved these changes
سلام خسته نباشید کد خوبی بود
فقط نکته ای که به ذهنم رسید داکیومنت نویسی زیاد هم خودش آفته کد باید خودش بتونه خودشو توصیف کنه
با توجه به اسم متد و و اسم کلاس ها
و حالا اگر خیلی جای گنگی وجود داشت داکیومنت اضافه بشه

2021-02-25 10:48 UTC, MRSadeghi78 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/TextFileReader.java
>      public String readTextFile(File file) {
سلام این تابع 
readTextFile
یه ذره طولش زیاده به نظرم، اگه بتونی به چندتا تابع مختلف تبدیلش کنی فکر کنم خوندنش راحتتر باشه

2021-02-25 11:12 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    private Set<Document> getIntersectionOfDocsContainingWords(Set<Token> tokens) {
ok 👌

2021-02-25 11:14 UTC, RAAvenger approved these changes

2021-02-25 11:19 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Token.java
> +        return content.toLowerCase();
A particular type of complexity is over-engineering, where developers have made the code more generic than it needs to be, or added functionality that isn’t presently needed by the system.
[https://google.github.io/eng-practices/review/reviewer/looking-for.html](url)

2021-02-25 11:21 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Document.java
> +    private final String fullPath;
در حال حاضر تمام داده‌ها توی مسیر مشخصی هستن و با استفاده از اسمشون میشه به راحتی پیداشون کرد.

2021-02-25 12:18 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/TextFileReader.java
>      public String readTextFile(File file) {
درسته این تابع بیش‌تر از ۱۰ خطی هست که در مستندات اومده ولی ماهیت کار تابع پیچیده نیست و طولانی شدن کد بیش‌تر به خاطر ساختار‌های کد مثل try catch هست

2021-02-25 12:19 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +    private static void startCLI() {
توضیح کوتاه اضافه شد.

2021-02-25 12:20 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/InvertedIndex.java
> +    public void addDocuments(Map<Document, String> docs) {
نام تابع واقعا واضح هست که چه کاری انجام میده

2021-02-25 12:23 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Document.java
> +    private final String fullPath;
چون اشیای مختلف داخل برنامه نباید به هم وابسته باشند پس محل ذخیره یک فایل در اصل مربوط به یک فایل هست و باید در اون شی مدیریت بشه

اگر بخواهیم با روش شما پیش‌بریم تابع اصلی برنامه باید مشخص کنه که هر فایل کجاست که به نظرم ارتباط بیش‌از حد نیاز هست.

2021-02-25 12:23 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +    private static ArrayList<String> getListOfWords(Scanner scanner) {
توضیح کوتاه اضافه شد.

2021-02-25 12:23 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +    private static void initializeEngine() {
تقریبا واضح هست ولی توضیح کوتاهی نوشتم

2021-02-25 12:25 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    public Set<Document> query(ArrayList<String> words) {
این تابع فقط وظیفه تشخیص برچسب را میده و یک تابع دیگه را صدا میزنه که وظیفه سرچ را داره 
ولی در نهایت نتیجه‌ای که کاربر از خروجی این تابع می‌بینه همون نتایج کوئری هست.

2021-02-25 12:25 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    public Set<Document> query(Set<Token> plusWords,
اضافه شد

2021-02-25 12:26 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    private Set<Document> getUnionOfDocsContainingWords(Set<Token> tokens) {
توضیح کوتاه اضافه شد.

2021-02-25 12:28 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Token.java
> +        return content.toLowerCase();
به نظرم مسئله نرمال‌سازی واقعا یک مسئله جدی هست
مثلا شما فرض کن که می‌خواهیم ریشه کلمات را هم تشخیص بدیم و با اون‌ها کار کنیم یا مثلا در مستنداتی که ساختار مشخصی دارند فقط بخش مشخصی را جدا کنیم 
در ساده ترین حالت که اینجا هست فقط کوچک‌سازی حروف انجام شده و کار دیگه‌ای لازم نبوده
اگر این تابع تعریف نشود در صورتی که برای نرمال‌سازی عمل دیگری هم لازم باشد باید تغییرات متعددی در برنامه داده بشه

2021-02-25 12:29 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/InvertedIndex.java
> +    public void addDocument(Document doc, String content) {
نام تابع و ساختار کد به اندازه کافی ساده هست که نیازی به کامنت نداره

2021-02-25 12:34 UTC, RAAvenger commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Token.java
> +        return content.toLowerCase();
به نظر من هم مساله جدی‌ای هست و حدس میزنم در مراحل دیگه نیاز بشه که کلا یک کلاس برای این کار تعریف کنیم ولی در این مرحله از اونجایی که تابعی که نوشتی واقعا کار خاصی انجام نمیده و اینجور هم نیست که به تعدد ازش استفاده شده باشه به نظرم اضافی میاد. البته خب من پول ریکوئست رو اپروو کردم چونکه به نظرم این امری که داریم درباره‌ش حرف میزنیم تاثیر چندانی روی نتیجه نهایی نداره.

2021-02-25 12:35 UTC, RAAvenger approved these changes

2021-02-25 19:30 UTC, MRSadeghi78 reviewed
در کل کدت خیلی تر تمیز و استاندارده 
تنها نکته ای که میخواستم بگم اینه که همونطور که آقای حیدرزاده هم گفتن تعداد کامنتا تو کدت یه ذره زیاده
مخصوصا تعداد زیادی از تابع ها هستن که اسمشون کاملا مشخص میکنه که دارن چیکار میکنن و نیازی به کامنت اضافه ندارن
البته اینم به نظر خودم خیلی ایراد به حساب نمیاد ولی اگه رعایت کنی فکر کنم کدت از لحاظ ظاهری و خوانایی یه ذره بهتر بشه

2021-02-25 19:30 UTC, MRSadeghi78 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/InvertedIndex.java
> +    public Set<Document> query(Token token) {
رضا اینو قبلا گفته ولی به نظر منم به جای اضافه کردن جاوا داک اگه اسم تابع رو تغییر بدی تا از رو اسمش بشه فهمید چیکار میکنه خیلی بهتره.
مثلا اینجا اسم
query
واقعا مفهوم خاصی رو به ذهن نمیاره

2021-02-25 19:30 UTC, MRSadeghi78 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +    private static boolean askToTerminate(Scanner scanner) {
بعضی جاهای کدت به نظرم اضافیه
مثلا اینجا تابع 
askToTerminate
از اسمش کاملا معلومه که میخواد چیکار کنه و نیازی به جاوا داک نداره

2021-02-25 19:30 UTC, MRSadeghi78 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    public Set<Document> query(ArrayList<String> words) {
اینجا هم به نظرم میشد به جای جاوا داک از یه اسم مناسبتر برای تابع استفاده کرد

2021-02-25 19:30 UTC, MRSadeghi78 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    public Set<Document> query(Set<Token> plusWords,
اینکه چندتا تابع با یه اسم توی کدت داری شاید یه کم باعث سردرگمی بشه، به نظرم اگه دقیقا یه کارو نمیکنن اسم های متفاوتی براشون بذار که فرقشون معلوم بشه

2021-02-25 19:55 UTC, MRSadeghi78 approved these changes

2021-02-25 20:03 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    public Set<Document> query(Set<Token> plusWords,
چند تا تابع با یک اسم به این دلیل هست که واقعا کاری که انجام می‌شه یکسان هست ولی با ورودی‌های متفاوت 
و هر تابع یک بخش کوچک از کار را ساده‌سازی انجام می‌ده و با فراخوانی یکی دیگه از توابع نتیجه را مشخص می‌کنه

2021-02-25 20:10 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
> +    public Set<Document> query(ArrayList<String> words) {
ممنون
اسم متغییر را تغییر دادم امیدوارم واضح‌تر شده باشه

2021-02-26 05:40 UTC, alrz1999 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Document.java
> +    private final String fullPath;
اگه به جای خوندن داکیومنت از فایل، بخوایم از دیتابیس یا یه جای دیگه بخونیم باید این فایل رو عوض کنیم و به نظرم احتیاجی نیست یه داکیومنت بدونه کجا قرار داره.

2021-02-26 05:40 UTC, alrz1999 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Document.java
> +    private final String name;
این
name
همون
id
عه داکیومنته یا عنوانش؟

2021-02-26 05:40 UTC, alrz1999 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Main.java
> +    private static void startCLI() {
به نظرم یه کلاس دیگه واسه خروجی دادن به کاربر لازمه چون ممکنه در آینده بخوایم به جای 
command line
 از یه طریق دیگه خروجی بدیم

2021-02-26 05:40 UTC, alrz1999 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
>          if (plusDocs.isEmpty()) {
الان اگه واسه 
or
هامون هیچ داکیومنتی پیدا نشه، نباید هیچی خروجی ندیم؟

2021-02-26 05:40 UTC, alrz1999 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Token.java
> +    public static Token[] textToTokens(String content) {
tokenizer
چرا حذف شد؟
الان اینا ربطی به 
token
نداره.

2021-02-26 05:40 UTC, alrz1999 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Token.java
> +        return content.toLowerCase();
با توجه به کاری که الان انجام میده همین یه تابع مناسبه ولی بعدا ممکنه کلاس جدا لازم باشه
و اینکه کارش هم ربطی به خود 
token
نداره و بهتره بره تو 
tokenizer

2021-02-26 09:19 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Document.java
> +    private final String name;
بله
شناسه داکیومنت و عنوان فایل یکسانه
نام فیلد را به 
id 
تغییر دادم

2021-02-26 11:17 UTC, mohammadhheidarzade approved these changes

2021-02-26 11:43 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/QueryEngine.java
>          if (plusDocs.isEmpty()) {
در صورتی که هر یک از مجموعه‌های بدون علامت یا با علامت مثبت خالی باشند
تمام اعضای مجموعه‌ی دیگر حساب می‌شوند 
ولی در صورتی که هر دو دارای تعداد داکیومنت باشند اشتراک محاسبه می‌شود.

و درنهایت در هر یک از صورت‌های ذکر شده مجموعه‌ی کلمات منفی‌دار حذف می‌شوند.

2021-02-26 11:51 UTC, MKasaei00 commented on phase 02/Winter99-codestar-inverted-index-search-java/src/Token.java
> +        return content.toLowerCase();
اصلاح شد

2021-02-26 13:35 UTC, RAAvenger approved these changes

2021-02-27 13:46 UTC, RAAvenger approved these changes

2021-02-27 19:55 UTC, alrz1999 approved these changes

2021-02-28 06:04 UTC, merged