phase 4 : Students and courses with C#
Star-Academy/Winter99-Codestar-Mohammad-Kasaei pull request #4
Opened 2021-03-06 19:38 UTC by MKasaei00

2021-03-06 19:54 UTC, mohammadhheidarzade requested changes

2021-03-06 19:54 UTC, mohammadhheidarzade commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        private static readonly string Path = "C:\\Mohammad\\work\\Mohaimen\\CodeStar\\codestar-winter\\Winter99-Codestar-Mohammad-Kasaei\\phase 04\\CSharpStudentAndScores\\";
path

2021-03-06 19:54 UTC, mohammadhheidarzade commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        private static IEnumerable<(string FirstName , string LastName , double Average)> FindTop3Students(List<Student> studentsList, List<ScoreRecord> scoresList)
چرا اسمارو همینطور ردیف کردی :))))
یه کلاس درست کن

2021-03-06 19:54 UTC, mohammadhheidarzade commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +            foreach (var (FirstName, LastName, Average) in filteredStudents)
کلاس درست کن واسش اسمارو ردیف نکن اینطوری

2021-03-06 19:54 UTC, mohammadhheidarzade commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        private static void PrintResults(IEnumerable<(string FirstName, string LastName, double Average)> filteredStudents)
و همین طور اینجا
کلاس درست کن
خیلی استفاده کردی ازین سه تا پارامتر

2021-03-06 19:54 UTC, mohammadhheidarzade commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +            (var Students, var Scores) = ReadInputFiles();
ورودی هارو توی خط جدا بگیر

2021-03-06 19:54 UTC, mohammadhheidarzade commented on phase 04/CSharpStudentAndScores/Scores.json
> +  {
داده هارو داخل ریپو پوش نمیکنن
اینارو داخل 
gitignore
بزار

2021-03-08 17:10 UTC, RAAvenger reviewed
کد جمع و جور و خوبی بود، ولی بهتره برای همین اندازه هم به 
S.O.L.I.D
دقت کنیم

2021-03-08 17:10 UTC, RAAvenger commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +                obj => obj.StudentNumber,
اسامی متفاوت انتخاب کنی خواناتر میشه

2021-03-08 17:10 UTC, RAAvenger commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +                .Take(3);
به جای نوع متغییر میتونی از 
var
استفاده کنی( موقع استفاده از 
LINQ
کار رایجیه
(
همچنین میتونی این کوئری بزرگ رو بشکونی به کوئری‌های کوچیکتر که خوانایی افزایش پیدا کنه.

2021-03-08 17:10 UTC, RAAvenger commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        }
single responsibility.

2021-03-08 17:10 UTC, RAAvenger commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +            PrintResults(FindTop3Students(studentsList, scoreRecords));
اینا رو توی یه تابع بنویسی تمیز تره

2021-03-08 18:06 UTC, mohammadhheidarzade approved these changes

2021-03-08 19:15 UTC, MKasaei00 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        }
تک کابری بودن در حد تابع رعابت شده و این تابع فقط وظیفه‌ی چاپ کردن را دارد

2021-03-08 19:15 UTC, MKasaei00 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +            PrintResults(FindTop3Students(studentsList, scoreRecords));
به نظرم چند تا کار ساده را پشت سر هم انجام میده و انتقال به یک تابع جدید بیش‌تر باعث پیچیده شدن کد میشه

2021-03-08 19:16 UTC, MKasaei00 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +                .Take(3);
قسمت‌های مختلف را تفکیک کردم

2021-03-09 14:10 UTC, MRSadeghi78 reviewed
خیلی خوب بود. خسته نباشی
صرفا یه نکته کوچیک به ذهنم رسید که گفتم

2021-03-09 14:10 UTC, MRSadeghi78 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        private static IEnumerable<StudentAverage> FindTop3Students(List<Student> studentsList, List<ScoreRecord> scoresList)
این تابع خیلی طولانی نیست؟
به نظرم میشه خیلی کوتاه تر و ساده تر نوشتش، با این حال اگه میخوای همین ساختار رو نگه داری به نظرم بهتره به چندتا تابع مختلف تقسیمش کنی

2021-03-09 14:40 UTC, MRSadeghi78 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        }
این بهتر نیست که یه کلاس جدا باشه؟
همون بحث
single responsibility

2021-03-09 14:41 UTC, MRSadeghi78 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +            var scoreRecords = JsonSerializer.Deserialize<List<ScoreRecord>>(scores);
اینا میتونن یه تابع جدا یا حتی یه کلاس جدا باشن

2021-03-09 16:08 UTC, MKasaei00 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        }
درسته
اصلاح شد

2021-03-09 16:08 UTC, MKasaei00 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        private static IEnumerable<StudentAverage> FindTop3Students(List<Student> studentsList, List<ScoreRecord> scoresList)
به صورت کوئری نوشتم خیلی کوتاه‌تر شد

2021-03-10 12:25 UTC, RAAvenger approved these changes

2021-03-10 13:12 UTC, alrz1999 requested changes

2021-03-10 13:12 UTC, alrz1999 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/FileReader.cs
> +        string path;
دلیلی داره که این
private
نیست؟

2021-03-10 13:12 UTC, alrz1999 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        private static IEnumerable<StudentAverage> FindTop3Students(List<Student> studentsList, List<ScoreRecord> scoresList)
این میتونست 
generic
تر باشه و مثلا یه عدد ورودی بگیره و که تعداد خروجی هاش باشه

2021-03-10 13:12 UTC, alrz1999 commented on phase 04/CSharpStudentAndScores/CSharpStudentAndScoresConsoleApp/Program.cs
> +        private static IEnumerable<StudentAverage> FindTop3Students(List<Student> studentsList, List<ScoreRecord> scoresList)
جاش هم تو
Program
نیست به نظرم

2021-03-10 15:17 UTC, alrz1999 approved these changes

2021-03-10 16:50 UTC, RAAvenger approved these changes

2021-03-10 17:32 UTC, merged